
spring:
  application:
    name: devsShop

  datasource:
    url: jdbc:mysql://localhost:3306/bookmngr
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

server:
  port: 8080

