
spring:
  application:
    name: devsShop
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

server:
  port: 8080

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true       # 실행되는 SQL 출력

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 바인딩되는 파라미터 출력
    org.hibernate.orm.jdbc.bind: trace                   # (Hibernate 6.x 권장) 파라미터 출력
    org.hibernate: warn             # Hibernate 전반 로그 레벨 (default: info)